Cleanup, pt. 2
flamingchickens1540/robot2024 pull request #33
Opened 2024-02-13 01:04 UTC by mimizh2418

Minor code cleanup and less scuffed logging of active pathplanner path

2024-02-13 15:58 UTC, rutmanz requested changes
Oops wrong button

2024-02-13 16:56 UTC, mimizh2418 commented on src/main/java/org/team1540/robot2024/RobotContainer.java
> -
They were already in drivetrain

2024-02-13 16:59 UTC, mimizh2418 commented on src/main/java/org/team1540/robot2024/util/PathHelper.java
> +            Constants.Drivetrain.MAX_ANGULAR_SPEED * (4.0/3.0)
I'm changing the path constraints to be defined by the actual limits of the robot (also yeah i forgot to do that for translation), is there some reason why we shouldn't do this?

2024-02-14 07:17 UTC, rutmanz commented on src/main/java/org/team1540/robot2024/util/PathHelper.java
> +            Constants.Drivetrain.MAX_ANGULAR_SPEED * (4.0/3.0)
No why specifically 4/3

2024-02-14 07:18 UTC, rutmanz commented on src/main/java/org/team1540/robot2024/RobotContainer.java
> -
Even the sim specific stuff?

2024-02-14 20:03 UTC, mimizh2418 commented on src/main/java/org/team1540/robot2024/util/PathHelper.java
> +            Constants.Drivetrain.MAX_ANGULAR_SPEED * (4.0/3.0)
The ratio before was 4/3 (720/540) so it just keeps the same acceleration time

2024-02-14 20:09 UTC, mimizh2418 commented on src/main/java/org/team1540/robot2024/RobotContainer.java
> -
AFAIK the sim specific stuff just makes pathplanner log the current pose and target pose as the same thing, which doesn't seem necessary

2024-02-14 20:17 UTC, mimizh2418 commented on src/main/java/org/team1540/robot2024/util/PathHelper.java
> +        this.shouldFlip = shouldFlip;
Is this variable even necessary? It's not being used anywhere and the flipping doesn't use it

2024-02-15 02:42 UTC, rutmanz approved these changes

2024-02-16 04:50 UTC, rutmanz approved these changes

2024-02-16 05:14 UTC, merged