Nate/autos
flamingchickens1540/robot2024 pull request #40
Opened 2024-03-07 23:54 UTC by belowAverageCoder5188

Adds autos AmpLanePdSprint, AmpLanePAB, AmpLanePA, AmpLanePADEF, AmpLaneChaos, AmpLanePDEFGH, CenterLaneP, CenterLanePB, CenterLanePBC, SourceLanePhSprint, and SourceLanePHGFED. _All are untested._

2024-03-18 04:43 UTC, rutmanz requested changes
Left feedback on paths as I looked through them on choreo, haven't taken a look at the commands yet. Some of them seem to be there in generated form but not in choreo, so I can't see what they look like

2024-03-18 04:43 UTC, rutmanz commented on src/main/deploy/choreo/AmpLaneChaos.traj
I can't seem to find this in paths.chor, is it vestigial?

2024-03-18 04:43 UTC, rutmanz commented on src/main/deploy/choreo/AmpLanePA.traj
You want to think about intake angle, and shot angle. It will try to align its yaw when shooting, but to intake successfully it really wants to be driving in the same direction it faces. Don't be afraid to add extra path points

2024-03-18 04:43 UTC, rutmanz commented on src/main/deploy/choreo/AmpLanePAB.traj
The robot will also want to move past the note, the "front" of the robot that you see in choreo wants to be completely past the far side of the note (so the note is contained in the robot box) for it to be happy

2024-03-18 04:43 UTC, rutmanz commented on src/main/deploy/choreo/AmpLanePADEF.traj
This one does pretty well with the intake angle (make sure to drive over the notes), but we're not consistent enough with shots from the wing line for this to be feasible, the shooting point should probably be closer to ~halfway between the podium and wing line

2024-03-18 04:43 UTC, rutmanz commented on src/main/deploy/choreo/AmpLanePDEFGH.traj
While we can shoot from under the stage (great job taking advantage of that), it does need to be a little closer forward and to the side so the shots don't get blocked by the chain. Also you may be interested by translation-only waypoints, that don't require a specific heading but do get you around obstacles

2024-03-18 04:43 UTC, rutmanz commented on src/main/deploy/choreo/AmpLanePdSprint.traj
Vestigial?

2024-03-18 04:43 UTC, rutmanz commented on src/main/deploy/choreo/SourceLanePHGFED.traj
I'm interested to see what this one looks like, but I don't see it in choreo

2024-03-18 22:33 UTC, belowAverageCoder5188 commented on src/main/deploy/choreo/AmpLaneChaos.traj
It should be in paths.chor, is in not on line 3119?

2024-03-20 23:04 UTC, belowAverageCoder5188 commented on src/main/deploy/choreo/AmpLanePA.traj
Fixed!

2024-04-02 23:01 UTC, closed without merging